# Generated by Django 2.1.2 on 2018-11-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rescatado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('nombre', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('tipoCasa', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
            ],
        ),
    ]
